// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy6BTzwgnhXUNCS8bz2qRswfSfu6Fdjak',
    appId: '1:723991587661:web:822ff9f98a06cf87dd6504',
    messagingSenderId: '723991587661',
    projectId: 'authentication-47be6',
    authDomain: 'authentication-47be6.firebaseapp.com',
    storageBucket: 'authentication-47be6.appspot.com',
    measurementId: 'G-C1RPFWCXPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeHtlPsTr2NISbgFHl5XBQJcKdSpTEB4w',
    appId: '1:723991587661:android:f62ec1e9bfd91b53dd6504',
    messagingSenderId: '723991587661',
    projectId: 'authentication-47be6',
    storageBucket: 'authentication-47be6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw-wgEPgZniNk7mTls0XxCWSHcxwO5828',
    appId: '1:723991587661:ios:97f86b8cf9652f42dd6504',
    messagingSenderId: '723991587661',
    projectId: 'authentication-47be6',
    storageBucket: 'authentication-47be6.appspot.com',
    androidClientId: '723991587661-hj53pgqffok6n324v08bfj8fmm6e142h.apps.googleusercontent.com',
    iosClientId: '723991587661-2ecd81dior2kepf4l88hkpbdncse1elt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw-wgEPgZniNk7mTls0XxCWSHcxwO5828',
    appId: '1:723991587661:ios:97f86b8cf9652f42dd6504',
    messagingSenderId: '723991587661',
    projectId: 'authentication-47be6',
    storageBucket: 'authentication-47be6.appspot.com',
    androidClientId: '723991587661-hj53pgqffok6n324v08bfj8fmm6e142h.apps.googleusercontent.com',
    iosClientId: '723991587661-2ecd81dior2kepf4l88hkpbdncse1elt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd_VpelAxAJI1Ldy48kiWK-Sqe58z9rS4',
    appId: '1:723991587661:web:a633cb1de442b4a1dd6504',
    messagingSenderId: '723991587661',
    projectId: 'authentication-47be6',
    authDomain: 'authentication-47be6.firebaseapp.com',
    storageBucket: 'authentication-47be6.appspot.com',
    measurementId: 'G-8K8THTTJB9',
  );
}
